### PR TITLE
CMake: Skip looking for C/C++ compiler

### PR DESCRIPTION
**Pull request by thopiekar**

### CODE REVIEW

**Comment by fieldOfView** [comment]
Out of interest, what does this change?
(Some description might have been useful)

**Comment by thopiekar** [comment]
Sorry. CMake checks by default for a C/C++ compiler. Adding this NONE tells CMake that there is no need to check for any compiler at all. Of course you could tell this way that this project is a Python project, but as far as I read CMake wouldn't understand it.
So in short: it tells CMake what's the main language of the whole project.

**Comment by fieldOfView** [comment]
Ok, that explains it. Thanks!

**Comment by thopiekar** [comment]
No problem. Sorry again for my laziness 😉

Mit freundlichen Grüßen/With kind regards
- Thomas Karl Pietrowski

Am 07.09.2016 15:36 schrieb "Aldo Hoeben" <notifications@github.com>:

**Pull request merged**
